name: Run compliance on insecure branch
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the insecure branch
  push:
    branches: [ main, insecure ]
  pull_request:
    branches: [ main, insecure ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
          
      # Runs a shell script using the runners shell
      - name: Run a shell script
        id: run-shell-script
        run: |
          echo Set execute permission.
          chmod +x "${GITHUB_WORKSPACE}/scripts/artifactory_compliance.sh"
          echo Run script.
          ./scripts/artifactory_compliance.sh
          
      - name: Check compliant file existence
        id: check_compliant
        uses: andstor/file-existence-action@v1
        with:
          files: "COMPLIANT.txt"
          
      - name: Check non compliant file existence
        id: check_non_compliant
        uses: andstor/file-existence-action@v1
        with:
          files: "NONCOMPLIANT.txt"
          
      - name: Non compliant file exists
        if: steps.check_non_compliant.outputs.files_exists == 'true'
        # Only runs if non compliant
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Failed compliance')
            
      - name: Display compliance if previous step succeeds
        if: ${{ success() }}
        run: echo "The compliance is ${{ steps.check_non_compliant.outputs.files_exists }}"
        

        
