name: run-shell-script
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a shell script using the runners shell
      - name: Run a shell script
      - run: |
           # make file runnable
           chmod +x "${GITHUB_WORKSPACE}/scripts/artifactory_compliance.sh"
           ./scripts/artifactory_compliance.sh
        
        
